### ISSUE TITLE
/var/www/kibana/src/config.js does not exist

### ISSUE THREAD

**Issue by brainstorm** [bakhti/ansible-elk#1]
Using the following ubuntu image in a VirtualBox `Vagrantfile`:

config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

```
TASK: [elk | Modify config.js] ************************************************
failed: [default] => {"failed": true, "rc": 257}
msg: Destination /var/www/kibana/src/config.js does not exist !

FATAL: all hosts have already failed -- aborting
```

**Comment by brainstorm** [comment]
Seems that the new master branch for Kibana is 4.0.0beta3, so the mechanism that used to work for deploying Kibana3 is broken now.

Seems that @ansible git module does not allow checking out a specific branch, so adding an additional step to checkout the `kibana3` or `3.0` branches should do the trick.

@carles

**Comment by brainstorm** [comment]
Strike my last comment, this is not the problem since `v3.0.1` **tag** still exists and should get checked out correctly via ansible's git module `version` parameter...

**But**, after the error above I `vagrant ssh` into the VM and discover that the `/var/www` directory is not there:

```
vagrant@localhost:~$ ls -alh /var/www
ls: cannot access /var/www: No such file or directory
```

**Comment by bakhti** [comment]
Sorry that it took so long for me to respond you, I was on vacation, and thank you for your support. I've merged your pull request, it doesn't feel right though, because since `config.js` is modified all the related tasks are `changed` again on the next playbook run.
So I've set `changed_when` to `false` for such tasks and added a `travis` check to see that Kibana is up.

**Comment by brainstorm** [comment]
No worries, thanks for this excellent role, you did a remarkable job here :+1:
